### ISSUE TITLE
Native Node Modules e.g. USB

### ISSUE THREAD

**Issue by TomFuch** [daltonmenezes/electron-app#21]
Hi!

Is it possible to use a native module like usb? Currently if i install this module I got an error:

App threw an error during load
Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=110 uv=1 armv=8 libc=glibc node=16.17.1 electron=22.2.1

Thanks for hints...

**Comment by daltonmenezes** [comment]
Hi, @TomFuch what is the npm package name you are trying to use?

**Comment by TomFuch** [comment]
Hi, @daltonmenezes !

https://github.com/node-usb/node-usb 

In the meantime I found a solution that works for me. 
In electron.vite.config.js -> build -> rollupOptions -> externals: ['usb'].
With that key it works for dev and build... 🤗
