### ISSUE TITLE
electron-notarize is deprecated

### ISSUE THREAD

**Issue by kruulik** [daltonmenezes/electron-app#26]
https://www.npmjs.com/package/electron-notarize
> Please use @electron/notarize moving forward. There is no API change, just a package name change
Electron-notarize has been deprecated, and should be replaced with @electron/notarize

**Comment by daltonmenezes** [comment]
Hi @kruulik , as the notarize package is not a direct dependency of electron-app (I believe it is a dependency of electron-builder), you should try to update the electron-builder version in your repo!
