### ISSUE TITLE
Database connection package problem

### ISSUE THREAD

**Issue by venkatsdesktop** [daltonmenezes/electron-app#27]
**Node version : v20.11.1
NPM version :10.2.4
Yarn version : 1.22.21**

**While install sequelize  - Success** 

`yarn add sequelize`

![image](https://github.com/daltonmenezes/electron-app/assets/162733540/3225ce4b-7512-4972-9eee-f396ba6563bf)

**While install sqlite3 or mysql  - failed** 

`yarn add sqlite3`

![image](https://github.com/daltonmenezes/electron-app/assets/162733540/e73daf82-14df-4495-b010-5ddf6d8dd9f0)

Any one kindlyy help me this one issue.  same like I try to install TypeORM & bookshelf packages , getting same errror message,

**Comment by daltonmenezes** [comment]
Hi @venkatsdesktop , I just tried to install both of dependencies and the installation works as expected on `node v18.19.1`, and the version of electron that electron-app install is [v25 where electrons ships the node v18](https://releases.electronjs.org/release/v25.0.0). I recommend you to work in the same node version that electrons ships!

About the sqlite3 in node 20, you should report it on the [sqlite3 repo](https://github.com/TryGhost/node-sqlite3) or try to use [better-sqlite3](https://www.npmjs.com/package/better-sqlite3) package instead!
