### ISSUE TITLE
'yarn dist' is not working

### ISSUE THREAD

**Issue by daskabe** [daltonmenezes/electron-app#3]
Steps

1. clone repo
2. yarn 
3. yarn dev  - make sure app works - it does
4. yarn dist - executes correctly but no dist folder created in project folder. (per the README)
From `package.json` and `electron-builder.js` configurations  it seems this is the path its going to drop the build at.
`  "devTempBuildFolder": "./node_modules/.dev-temp-build",`    
But I don't see dist folder there either. 

![image](https://user-images.githubusercontent.com/94478096/168625081-5e796931-e1ab-4cd0-84f4-3c6e1a6aec7f.png)

**Comment by daltonmenezes** [comment]
@daskabe as mentioned in the [docs](https://github.com/daltonmenezes/electron-app#for-a-specific-one):
```js
yarn dist --mac
# OR
yarn dist --win
# OR
yarn dist --linux
```
You can't build for all platforms using the same operating system, for this take a look at [releasing section](https://github.com/daltonmenezes/electron-app#-releasing)

**Comment by daskabe** [comment]
@daltonmenezes  Its doing weird stuff like opening VScode to `electron-builder.js` file in middle of build. I attached vid of what i am seeing. I am running it in powershell admin this time.

running `yarn electron-builder --win` works fine in the same powershell I used for the vid.  

https://user-images.githubusercontent.com/94478096/168666283-42975c26-9d86-48ed-9748-835137344754.mp4

**Comment by daltonmenezes** [comment]
@daskabe please, update your dist script on package.json file to:
```js
"dist": "./node_modules/.bin/electron-builder",
```

**Comment by daskabe** [comment]
Yep that fixed it. thanks

**Comment by daltonmenezes** [comment]
@daskabe thanks for the feedback. As soon as possible, I'm going to update the dist script to make it cross-platform with that solution 💜

**Comment by daskabe** [comment]
Thank you for great electron starter!
