### ISSUE TITLE
Hot Reload always render whole Page

### ISSUE THREAD

**Issue by TomFuch** [daltonmenezes/electron-app#9]
If something change in screens/Main/index.tsx the whole Page is rerenderd and all react state is gone...

**Comment by daltonmenezes** [comment]
@TomFuch done, thanks for the suggestion. Could you try it, please, and give me some feedback?

**Comment by TomFuch** [comment]
> @TomFuch done, thanks for the suggestion. Could you try it, please, and give me some feedback?

@daltonmenezes WOW - THANKS! Now it works like a charm!
